version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: sitetune-waha_server_1
      APP_PORT: 3000
    
  server:
    image: devlikeapro/waha:latest
    # user: "1000:1000"
    # init: trues
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 3002:3000
    volumes:
      - ${APP_DATA_DIR}/sessions:/app/.sessions
      - ${APP_DATA_DIR}/media:/app/.media
    environment:
      WHATSAPP_HOOK_URL: http://n8n:5678/webhook/webhook
      WHATSAPP_DEFAULT_ENGINE: GOWS
      WHATSAPP_HOOK_EVENTS: message
